---
vm_name: MR_factories
path: /MR_factories
git_branch: master
vm_os: ubuntu/trusty64
environments:
  - development
package_bundles:
  - curl
  - graphics
  - qt
packages:
  - curl
  - libcurl3
  - libcurl3-gnutls
  - libcurl4-openssl-dev
  - imagemagick
  - qt5-default
  - libqt5webkit5-dev
manual_ruby_version:
server_name: localhost
rails_version: 4
ruby_install: rvm
ruby_version: 2.2.0
environment_file: /MR_factories/.envrc
databases:
  - mysql
background_jobs:
postgresql_orm: none
mysql_orm: none
mongodb_orm: none
redis_orm: none
mongodb_db_name: myapp
mysql_db_name: MR
mysql_db_user: sa
mysql_db_password: dinz217
git_url: 

app_name: '{{ vm_name }}'
user_name: 'MR_factories' #{{ "vagrant" if target == "virtualbox" else app_name }}'
group_name: '{{ user_name }}'

user_home_path: '/home/{{ user_name }}'

ssl_certificate_path: /etc/nginx/ssl/{{ server_name }}.crt
ssl_certificate_key_path: /etc/nginx/ssl/{{ server_name }}.key

app_path: '{{ path if target == "virtualbox" else "{{ path }}/current" }}'
app_public_path: "{{ app_path }}/public"
app_config_path: "virtualbox/config"
app_temp_path: "{{ app_path }}/tmp"
app_logs_path: "{{ app_path }}/log"

releases_path: '{{ path }}/releases'
shared_path: '{{ path }}/shared'

ruby_user_name: '{{ "root" if ruby_install == "package" else user_name }}'

use_apt_proxy: false
