---
vim_autoload_path: '/home/MR_factories/.vim/autoload'
vim_bundle_path: '/home/MR_factories/.vim/bundle'
vim_plugins:
  - name: vim-sensible
    git: git://github.com/tpope/vim-sensible.git
  - name: vim-rails
    git: git://github.com/tpope/vim-rails.git
  - name: vim-bundler
    git: git://github.com/tpope/vim-bundler.git
