---

- hosts: all

  sudo: true

  tasks:

    - name: Update apt cache
      apt: update_cache=yes

    - name: Install apt dependencies
      apt: name={{ item }}
      with_items:
        - autoconf
        - bison
        - build-essential
        - libssl-dev
        - libyaml-dev
        - libreadline6-dev
        - zlib1g-dev
        - libncurses5-dev
        - nodejs
        - python-pip
        - python-dev
        - htop
        - git

    - name: Install CURL

      apt: name='{{ item }}'
      with_items:
        - curl
        - libcurl3
        - libcurl3-gnutls
        - libcurl4-openssl-dev
        - imagemagick
        - qt5-default
        - libqt5webkit5-dev

    - name: Install mysql packages
      apt: name='{{ item }}'
      with_items:
        - mysql-server
        - libmysqlclient-dev
        - python-pip
        - python-dev



    #- name: Install ruby #might want to use rvm instead

      #apt: name=ruby-full state=present
